FROM python:3.10-slim

# Set the working directory
WORKDIR /mlflow

# Install MlFlow
RUN pip install mlflow psycopg2-binary boto3 minio


# Set up the persistance 
# in docker-compose.yml
#ENV BACKEND_URI sqlite:///mlflow.db


# expose port
EXPOSE 5000

# Command to run Mlflow
#CDM mlflow ui --backend-store-uri $BACKEND_URI --host 0.0.0.0
